import React from "react";

export const BookShelfs = () => {
  const bookShelfArray = [
    "Adventure (Bookshelf)",
    "Africa (Bookshelf)",
    "African American Writers (Bookshelf))",
    "Ainslee's (Bookshelf)",
    "American Revolutionary War (Bookshelf)",
    "Anarchism (Bookshelf)",
    "Animal (Bookshelf)",
    "Animals-Domestic (Bookshelf)",
    "Animals-Wild (Bookshelf)",
    "Animals-Wild (Bookshelf)-Birds",
    "Animals-Wild (Bookshelf)-Insects",
    "Animals-Wild (Bookshelf)-Mammals",
    "Animals-Wild (Bookshelf)-Reptiles and Amphibians",
    "Animals-Wild (Bookshelf)-Trapping",
    "Anthropology (Bookshelf)",
    "Archaeology (Bookshelf)",
    "Architecture (Bookshelf)",
    "Argentina (Bookshelf)",
    "Armour's Monthly Cook Book (Bookshelf)",
    "Art (Bookshelf)",
    "Arthurian Legends (Bookshelf)",
    "Astounding Stories (Bookshelf)",
    "Astronomy (Bookshelf)",
    "Atheism (Bookshelf)",
    "Australia (Bookshelf)",
    "Bahá'í Faith (Bookshelf)",
    "Banned Books from Anne Haight's list (Bookshelf)",
    "Banned Books List from the American Library Association (Bookshelf)",
    "Barnavännen (Bookshelf)",
    "Best Books Ever Listings (Bookshelf)",
    "Bestsellers, American, 1895-1923 (Bookshelf)",
    "Bibliomania (Bookshelf)",
    "Biographies (Bookshelf)",
    "Biology (Bookshelf)",
    "Bird-Lore (Bookshelf)",
    "Birds, Illustrated by Color Photography (Bookshelf)",
    "Blackwood's Edinburgh Magazine (Bookshelf)",
    "Boer War (Bookshelf)",
    "Botany (Bookshelf)",
    "British Law (Bookshelf)",
    "Buchanan's Journal of Man (Bookshelf)",
    "Buddhism (Bookshelf)",
    "Bulgaria (Bookshelf)",
    "Bulletin de Lille (Bookshelf)",
    "Camping",
    "Canon Law",
    "Celtic Magazine (Bookshelf)",
    "Chambers's Edinburgh Journal (Bookshelf)",
    "Chemistry (Bookshelf)",
    "Child's Own Book of Great Musicians (Bookshelf)",
    "Children's Anthologies (Bookshelf)",
    "Children's Biography (Bookshelf)",
    "Children's Book Series (Bookshelf)",
    "Children's Fiction (Bookshelf)",
    "Children's History (Bookshelf)",
    "Children's Instructional Books (Bookshelf)",
    "Children's Literature (Bookshelf)",
    "Children's Myths, Fairy Tales, etc. (Bookshelf)",
    "Children's Periodicals (Bookshelf)",
    "Children's Picture Books (Bookshelf)",
    "Children's Religion (Bookshelf)",
    "Children's Verse (Bookshelf)",
    "Christianity (Bookshelf)",
    "Christmas (Bookshelf)",
    "CIA World Factbooks (Bookshelf)",
    "Classical Antiquity (Bookshelf)",
    "Contemporary Reviews (Bookshelf)",
    "Continental Monthly (Bookshelf)",
    "Cookbooks and Cooking (Bookshelf)",
    "Crafts (Bookshelf)",
    "Crime Fiction (Bookshelf)",
    "Crime Nonfiction (Bookshelf)",
    "Current History (Bookshelf)",
    "Czech (Bookshelf)",
    "De Aarde en haar Volken (Bookshelf)",
    "Detective Fiction (Bookshelf)",
    "Dew Drops (Bookshelf)",
    "Donahoe's Magazine (Bookshelf)",
    "Early English Text Society (Bookshelf)",
    "Education",
    "Egypt (Bookshelf)",
    "Engineering (Bookshelf)",
    "English Civil War (Bookshelf)",
    "Erotic Fiction (Bookshelf)",
    "Esperanto (Bookshelf)",
    "Famous Scots Series (Bookshelf)",
    "Fantasy (Bookshelf)",
    "Folklore (Bookshelf)",
    "Forestry",
    "France (Bookshelf)",
    "Garden and Forest (Bookshelf)",
    "General Fiction",
    "Geology (Bookshelf)",
    "German Language Books (Bookshelf)",
    "Germany (Bookshelf)",
    "Godey's Lady's Book (Bookshelf)",
    "Golden Days for Boys and Girls (Bookshelf)",
    "Gothic Fiction (Bookshelf)",
    "Graham's Magazine (Bookshelf)",
    "Greece (Bookshelf)",
    "Harper's New Monthly Magazine (Bookshelf)",
    "Harper's Young People (Bookshelf)",
    "Harvard Classics (Bookshelf)",
    "Hinduism (Bookshelf)",
    "Historical Fiction (Bookshelf)",
    "Horror (Bookshelf)",
    "Horticulture (Bookshelf)",
    "Humor (Bookshelf)",
    "Illustrators (Bookshelf)",
    "India (Bookshelf)",
    "Islam (Bookshelf)",
    "Italy (Bookshelf)",
    "Journal of Entomology and Zoology (Bookshelf)",
    "Judaism (Bookshelf)",
    "L'Illustration (Bookshelf)",
    "Language Education (Bookshelf)",
    "Latter Day Saints (Bookshelf)",
    "Lippincott's Magazine (Bookshelf)",
    "Little Folks (Bookshelf)",
    "London Medical Gazette",
    "Love (Bookshelf)",
    "Manufacturing",
    "Maps and Cartography (Bookshelf)",
    "Masterpieces in Colour (Bookshelf)",
    "Mathematics (Bookshelf)",
    "McClure's Magazine (Bookshelf)",
    "Medicine (Bookshelf)",
    "Mediæval Town Series (Bookshelf)",
    "Microbiology (Bookshelf)",
    "Microscopy (Bookshelf)",
    "Mother Earth (Bookshelf)",
    "Movie Books (Bookshelf)",
    "Mrs Whittelsey's Magazine for Mothers and Daughters (Bookshelf)",
    "Music (Bookshelf)",
    "Mycology (Bookshelf)",
    "Mystery Fiction (Bookshelf)",
    "Mythology (Bookshelf)",
    "Napoleonic(Bookshelf)",
    "Native America (Bookshelf)",
    "Natural History (Bookshelf)",
    "New Zealand",
    "Northern Nut Growers Association (Bookshelf)",
    "Norway (Bookshelf)",
    "Notes and Queries (Bookshelf)",
    "Noteworthy Trials(Bookshelf)",
    "One Act Plays (Bookshelf)",
    "Opera (Bookshelf)",
    "Our Young Folks (Bookshelf)",
    "Paganism (Bookshelf)",
    "Philosophy (Bookshelf)",
    "Photography (Bookshelf)",
    "Physics (Bookshelf)",
    "Physiology (Bookshelf)",
    "Pirates, Buccaneers, Corsairs, etc. (Bookshelf)",
    "Plays (Bookshelf)",
    "Poetry (Bookshelf)",
    "Poetry, A Magazine of Verse (Bookshelf)",
    "Politics (Bookshelf)",
    "Popular Science Monthly (Bookshelf)",
    "Prairie Farmer (Bookshelf)",
    "Precursors of Science Fiction (Bookshelf)",
    "Project Gutenberg (Bookshelf)",
    "Psychology (Bookshelf)",
    "Punch (Bookshelf)",
    "Punchinello (Bookshelf)",
    "Racism (Bookshelf)",
    "Reference (Bookshelf)",
    "Romantic Fiction (Bookshelf)",
    "School Stories (Bookshelf)",
    "Science",
    "Science Fiction (Bookshelf)",
    "Science Fiction by Women (Bookshelf)",
    "Scientific American (Bookshelf)",
    "Scouts (Bookshelf)",
    "Scribner's Magazine (Bookshelf)",
    "Short Stories (Bookshelf)",
    "Slavery (Bookshelf)",
    "Sociology (Bookshelf)",
    "South Africa (Bookshelf)",
    "South America (Bookshelf)",
    "Spanish American War (Bookshelf)",
    "St. Nicholas Magazine for Boys and Girls (Bookshelf)",
    "Suffrage",
    "Technology (Bookshelf)",
    "The Aldine (Bookshelf)",
    "The American Architect and Building News (Bookshelf)",
    "The American Bee Journal (Bookshelf)",
    "The American Journal of Archaeology (Bookshelf)",
    "he American Missionary (Bookshelf)",
    "The American Quarterly Review (Bookshelf)",
    "The Arena (Bookshelf)",
    "The Argosy (Bookshelf)",
    "The Atlantic Monthly (Bookshelf)",
    "The Baptist Magazine (Bookshelf)",
    "The Bay State Monthly (Bookshelf)",
    "The Botanical Magazine (Bookshelf)",
    "The Brochure Series of Architectural Illustration (Bookshelf)",
    "The Catholic World (Bookshelf)",
    "The Christian Foundation (Bookshelf)",
    "The Church of England Magazine (Bookshelf)",
    "The Contemporary Review (Bookshelf)",
    "The Economist (Bookshelf)",
    "The Esperantist (Bookshelf)",
    "The Galaxy (Bookshelf)",
    "The Girls Own Paper (Bookshelf)",
    "The Great Round World And What Is Going On In It (Bookshelf)",
    "The Haslemere Museum Gazette (Bookshelf)",
    "The Idler (Bookshelf)",
    "The Illustrated War News (Bookshelf)",
    "The International Magazine of Literature, Art, and Science (Bookshelf)",
    "The Irish Ecclesiastical Record (Bookshelf)",
    "The Irish Penny Journal (Bookshelf)",
    "The Journal of Negro History (Bookshelf)",
    "The Knickerbocker (Bookshelf)",
    "The Mayflower (Bookshelf)",
    "The Menorah Journal (Bookshelf)",
    "The Mentor (Bookshelf)",
    "The Mirror of Literature, Amusement, and Instruction (Bookshelf)",
    "The Mirror of Taste, and Dramatic Censor (Bookshelf)",
    "The National Preacher (Bookshelf)",
    "The North American Medical and Surgical Journal (Bookshelf)",
    "The Nursery (Bookshelf)",
    "The Philatelic Digital Library Project (Bookshelf)",
    "The Scrap Book (Bookshelf)",
    "The Speaker (Bookshelf)",
    "The Stars and Stripes (Bookshelf)",
    "The Strand Magazine (Bookshelf)",
    "The Unpopular Review (Bookshelf)",
    "The Writer (Bookshelf)",
    "The Yellow Book (Bookshelf)",
    "Transportation (Bookshelf)",
    "Travel (Bookshelf)",
    "United Kingdom (Bookshelf)",
    "United States (Bookshelf)",
    "United States Law (Bookshelf)",
    "US Civil War (Bookshelf)",
    "Western (Bookshelf)",
    "Witchcraft (Bookshelf)",
    "Women's Travel Journals (Bookshelf)",
    "Woodwork",
    "World War I (Bookshelf)",
    "World War II (Bookshelf)",
    "Zoology (Bookshelf)",
  ];
};
